config/routes.rb
Rails.application.routes.draw do
  resources :facility_services
  resources :service_types
  resources :services
  resources :facilities
  resources :user_comments
  resources :comments
  resources :users
  resources :analytics


  get "/", to: "homes#index"
  get "/sessions/new", to: "sessions#new", as: "login" #login_path
  delete "/sessions", to: "sessions#destroy"
  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :facility
end

app/models/facility.rb
class Facility < ApplicationRecord
	has_many :user_comments
	has_many :comments, through: :user_comments
	has_many :users, through: :user_comments
	
	has_many :facility_services
	has_many :services, through: :facility_services
end

app/models/facility_service.rb
class FacilityService < ApplicationRecord
  belongs_to :facility
  belongs_to :service
end

app/models/service.rb
class Service < ApplicationRecord

	has_many :facility_services, :dependent => :destroy
	has_many :facilities, through: :facility_services
end

app/models/service_type.rb
class ServiceType < ApplicationRecord
	has_many :services
end

app/models/user.rb
class User < ApplicationRecord
	has_many :user_comments
	has_many :comments, through: :user_comments
	has_secure_password

	validates :username, presence: true, length: {in: 3..16}
end

app/models/user_comment.rb
class UserComment < ApplicationRecord
  belongs_to :user
  belongs_to :comment
  belongs_to :facility
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		facility = Facility.find(params[:facility][:id])
		comment = Comment.create!(description: params[:description], facility: facility, user: current_user)
		UserComment.create!(user: current_user, comment: comment, facility: facility)
		redirect_to facility
	end

	def destroy
		facility = Facility.find(params[:facility][:id])
		comment = Comment.find(params[:id])
		if current_user == comment.user
			UserComment.find_by(comment: comment).destroy
		end
		redirect_to facility
		# byebug
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def index
		redirect_to "/users/new"
	end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController


    def new
    	# binding.pry
    end


    def index
    	# binding.pry
    end

   
   	def show
     
   		@service_type = ServiceType.find_by(name: params[:service][:service_type])
      @icon = ""
      case @service_type.name  #code to decide which icon to render
      when "Kitchen"
        @icon = "food_icon.png"
      when "Hygeine"
        @icon = "bath_icon.png"
      when "Shelter"
        @icon = "bed_icon.png"
      end
   		@services = Service.where(service_type: @service_type.id)
   		@service_name = @service_type.name
		  render :show
	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorized, except: [:new, :create]
  

  def index
    
  end
	def new
    # GET /users/new
    if logged_in?
      redirect_to "/services"
    end
    @user = User.new
  end

  def create
    @user = User.create(new_params)
    if @user.valid?
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end 

  private

  def new_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/helpers/service_types_helper.rb
module ServiceTypesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_comments_helper.rb
module UserCommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_welcome.html.erb
<!-- 
<div class='header'>
	<br>
<section>
  <%= link_to image_tag("bath_icon.png", class: 'image-size'), service_path(:service => {:service_type => 'Hygeine'})%><br> <h1>Hygeine Services</h1>
</section>


<section>
  <code><%= link_to image_tag("bed_icon.png", class: 'image-size'), service_path(:service => {:service_type => 'Shelter'})%><br> <h1>Shelter Services</h1></code>
</section>

<section>
  <code><%= link_to image_tag("food_icon.png", class: 'image-size'), service_path(:service => {:service_type => 'Kitchen'})%><br> <h1>Food Services</h1></code>
</section>
</div>
 -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelpFinder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">


    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Abel" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body >
    <br>
    <div class="container">
      <div class="columns is-centered">
       <div class="column is-half">



<nav class="level">
  <p class="level-item has-text-centered">
          <%= image_tag("Artboard 1.png",style: 'height:80px;width:auto;text-align: center')%>
  <p class="level-item has-text-centered">
    
    <h1><%= link_to "Home", users_path(@user), class: "link is-info" %></h1>
  </p>
  <p class="level-item has-text-centered">
    <h1><%= link_to "Services", "/services", class: "link is-info" %></h1>
    <!-- <a class="link is-info">Services</a> -->
  </p>
  <br><br>
  </p>

  <% if logged_in? %>
  <p class="level-item has-text-centered">
    <%= form_with url: '/sessions', method: 'delete' do |f| %>
      <%= f.submit value: "Logout", class: "button" %>
    <% end %>
  </p>
  <% else %>
  <p class="level-item has-text-centered">
  <h1>  <%= link_to "Register", "/users/new" %>
  </p></h1>
  <p class="level-item has-text-centered"><h1>
    <%= link_to "Login", "/sessions/new" %>
  </p></h1>
  <% end %>
</nav>

       </div>
     </div>
   </div><br><br>
    <%= yield %>

  
  </body>

</html>